# 自动周报/月报生成配置（可按页面实际调整选择器）。
# 说明：不同账号/版本 DOM 结构可能差异很大，以下选择器为默认值，
# 如运行报错或截图不完整，请根据浏览器开发者工具更新相应选择器。

# 目标地址
trade_overview_url: 'https://ecom.meituan.com/bizguide/portal?cate=100057633#https://ecom.meituan.com/bizguide/trade-analysis/overview'
flow_overview_url:  'https://ecom.meituan.com/bizguide/portal?cate=100057632#https://ecom.meituan.com/bizguide/flow-analysis/overview'
cpc_url:            'https://ecom.meituan.com/bizguide/portal?cate=100057653#https://midas.dianping.com/shopdiy/account/pcCpcEntry?fromSourceType=hideHeader-DCjycm1&continueUrl=/promotionReport/html/index.html'

# 选择器（优先用于 trade_overview 页）
selectors:
  # 门店筛选下拉按钮（点击后打开弹窗）
  store_filter_button: '//div[contains(@class,"selector")]//span[contains(., "门店")]|//span[contains(.,"选择门店")]/..'
  # 弹窗内搜索输入框
  store_search_input: '//input[@placeholder="门店ID/门店名称/城市"]|//input[@type="text"]'
  # 弹窗内门店表格行（按门店ID精准匹配）
  store_table_row_by_id_tpl: '//table[contains(@class,"mtd-table-body")]//tr[.//td[2]//div[normalize-space(text())="{store_id}"]]'
  # 行内复选框（相对行定位）
  row_checkbox_rel: './/input[contains(@class,"mtd-checkbox-input")]'
  # 弹窗确认按钮
  store_confirm_btn: '//button[contains(.,"确定")]|//span[text()="确定"]/..'
  # 顶层弹窗的“清空已选”与“确定”绝对 XPath（用户环境提供，优先尝试）
  clear_selected_xpath: '/html/body/div[6]/div[2]/div[2]/div[2]/div/div[2]/div[2]/div[1]/div[3]'
  store_modal_confirm_xpath: '/html/body/div[6]/div[2]/div[2]/div[2]/div/div[2]/div[2]/div[2]/button[2]'

  # 检测“已选全部”输入框（读取 value 文案用）
  store_input_value: '//div[contains(@class,"poiSelectorInput")]//input[@type="text"]'

  # 核心指标区域（用于截图）。推荐使用能唯一定位到红框区域的容器节点
  trade_core_box: '//div[contains(.,"核心指标")]/ancestor::div[contains(@class,"card")][1]|//div[@id="app"]//div[contains(@class,"overview")][1]'
  # 为“大范围截图”提供一个靠近核心指标卡片上方的锚点（如页面顶部导航容器）
  page_top_anchor: '//div[@id="app"]//div[contains(@class,"crumb")] | //div[@id="app"]//header'

  # 单周选择与趋势按钮
  week_button: '//button[@value="WEEK"]'
  datepicker_trigger: '//*[@id="datePickerContainer"]//input|//*[@id="datePickerContainer"]//i[contains(@class,"calendar")]'
  week_row_tpl: '//div[contains(@class,"mtd-week-panel-row")][.//div[contains(@class,"mtd-week-panel-row-header-color") and normalize-space(text())="{week_no}"]]'
  trend_button: '//button[@value="1"]|//button[.//span[text()="店均及同行趋势"]]'
  trend_box: '//div[contains(@class,"trend")]'

# 截图参数
screenshot:
  scale: 'css'          # Playwright screenshot scale: 'css' 或 'device'
  full_page_fallback: true  # 若找不到容器则回退整页截图

# Excel 输出
excel:
  output_dir: 'data/reports'   # 统一输出目录
  image_column: 'A'            # 截图粘贴列
  image_row: 5                 # 截图粘贴起始行（1-based）
  width: 1200                  # 调整列宽像素（写入后自动适配）


